export interface CropTechnicalSheetData {
  id: string;
  crop_key: string;
  name_fr: string;
  category: string;
  cycle_days_min: number;
  cycle_days_max: number;
  climate_zones: string[];
  seasons: string[];
  npk_needs: { N: number; P: number; K: number };
  water_needs_mm: number;
  common_pests: string[];
  common_diseases: string[];
  recommended_varieties: string[];
  yield_potential_t_ha: number;
  notes: string;
  iconEmoji: string;
}

export const WEST_AFRICA_12_CROPS: CropTechnicalSheetData[] = [
  {
    id: "sheet-mais",
    crop_key: "mais",
    name_fr: "Maïs (Zea mays)",
    category: "Céréales",
    cycle_days_min: 80,
    cycle_days_max: 120,
    climate_zones: ["Soudanien", "Soudano-sahélien", "Guinéen"],
    seasons: ["Hivernage (Pluviale)", "Contre-saison irriguée"],
    npk_needs: { N: 100, P: 50, K: 50 },
    water_needs_mm: 550,
    common_pests: ["Chenille légionnaire d'automne (Spodoptera frugiperda)", "Foreurs de tiges (Sesamia)", "Charançons des stocks"],
    common_diseases: ["Helminthosporiose", "Rouille commune", "Strie du maïs (MSV)"],
    recommended_varieties: ["Barkas", "Bondofa", "Kabras", "Espoir (QPM)", "FBC6"],
    yield_potential_t_ha: 5.5,
    notes: "Exige un apport fractionné en urée (au semis/démariage puis au tallage/montaison). Forte sensibilité au déficit hydrique pendant la floraison.",
    iconEmoji: "🌽",
  },
  {
    id: "sheet-riz",
    crop_key: "riz",
    name_fr: "Riz (Oryza sativa / glaberrima)",
    category: "Céréales",
    cycle_days_min: 90,
    cycle_days_max: 135,
    climate_zones: ["Soudanien", "Soudano-sahélien", "Bas-fonds aménagés"],
    seasons: ["Hivernage", "Contre-saison irriguée"],
    npk_needs: { N: 120, P: 60, K: 40 },
    water_needs_mm: 800,
    common_pests: ["Cécidomyie du riz (Orseolia oryzivora)", "Foreurs de tiges (Chilo)", "Oiseaux granivores"],
    common_diseases: ["Pyriculariose (Magnaporthe oryzae)", "Panachure jaune du riz (RYMV)", "Flétrissement bactérien"],
    recommended_varieties: ["TS2", "FKR 19", "FKR 62N (NERICA 4)", "FKR 64", "Orylux 6"],
    yield_potential_t_ha: 6.0,
    notes: "Nivellement rigoureux requis pour l'irrigation et la maîtrise de la lame d'eau. Désherbage précoce crucial les 30 premiers jours.",
    iconEmoji: "🌾",
  },
  {
    id: "sheet-sorgho",
    crop_key: "sorgho",
    name_fr: "Sorgho blanc / rouge (Sorghum bicolor)",
    category: "Céréales",
    cycle_days_min: 90,
    cycle_days_max: 140,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien"],
    seasons: ["Hivernage (Pluviale)"],
    npk_needs: { N: 60, P: 30, K: 30 },
    water_needs_mm: 400,
    common_pests: ["Punaise des panicules", "Cécidomyie du sorgho", "Striga hermonthica (adventice parasite)"],
    common_diseases: ["Anthracnose", "Charbon de la panicule", "Ergot du sorgho"],
    recommended_varieties: ["Framida (tolérante Striga)", "Sariaso 11", "Kapelga", "Soubatimi"],
    yield_potential_t_ha: 3.5,
    notes: "Grande tolérance à la sécheresse et aux sols pauvres. Clé de voûte de la résilience céréalière sahélienne.",
    iconEmoji: "🌾",
  },
  {
    id: "sheet-mil",
    crop_key: "mil",
    name_fr: "Mil pénicillaire (Pennisetum glaucum)",
    category: "Céréales",
    cycle_days_min: 75,
    cycle_days_max: 110,
    climate_zones: ["Sahel", "Soudano-sahélien"],
    seasons: ["Hivernage"],
    npk_needs: { N: 40, P: 20, K: 20 },
    water_needs_mm: 350,
    common_pests: ["Mineuse de l'épi (Heliocheilus albipunctella)", "Sauteriaux", "Oiseaux quelea"],
    common_diseases: ["Mildiou (Sclerospora graminicola)", "Charbon", "Rouille"],
    recommended_varieties: ["IKMP 5", "Misari 1", "SOSAT C88", "Toroniou"],
    yield_potential_t_ha: 2.5,
    notes: "Extrêmement rustique, adapté aux sols sableux sahéliens. Idéal en association avec le niébé.",
    iconEmoji: "🌾",
  },
  {
    id: "sheet-niebe",
    crop_key: "niebe",
    name_fr: "Niébé / Haricot (Vigna unguiculata)",
    category: "Légumineuses",
    cycle_days_min: 60,
    cycle_days_max: 85,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien"],
    seasons: ["Hivernage", "Contre-saison maraîchère"],
    npk_needs: { N: 15, P: 40, K: 30 },
    water_needs_mm: 300,
    common_pests: ["Thrips des fleurs (Megalurothrips sjostedti)", "Maruca vitrata", "Pucerons (Aphis craccivora)", "Bruchus en stockage"],
    common_diseases: ["Mosaïque du niébé (CYMV)", "Anthracnose", "Flétrissement fusarien"],
    recommended_varieties: ["KVx 399-05", "Komcallé", "Tiligré", "Yiisyandé", "KVx 745-11P"],
    yield_potential_t_ha: 2.0,
    notes: "Fixe l'azote atmosphérique (réduit les besoins azotés des cultures suivantes). Surveillance phytosanitaire rigoureuse à la floraison.",
    iconEmoji: "🫘",
  },
  {
    id: "sheet-arachide",
    crop_key: "arachide",
    name_fr: "Arachide (Arachis hypogaea)",
    category: "Légumineuses & Oléagineux",
    cycle_days_min: 90,
    cycle_days_max: 120,
    climate_zones: ["Soudano-sahélien", "Soudanien", "Guinéen"],
    seasons: ["Hivernage"],
    npk_needs: { N: 20, P: 50, K: 40 },
    water_needs_mm: 450,
    common_pests: ["Iules (mille-pattes)", "Termites", "Pucerons vecteurs de la rosette"],
    common_diseases: ["Rosette de l'arachide", "Cercosporiose précoce et tardive", "Aspergillus flavus (aflatoxines)"],
    recommended_varieties: ["SH 470 P", "RMP 12", "Fleur 11", "QH 243 C"],
    yield_potential_t_ha: 3.0,
    notes: "Nécessite un sol meuble et bien drainé pour la pénétration des gynophores. Séchage rapide au champ indispensable contre les moisissures.",
    iconEmoji: "🥜",
  },
  {
    id: "sheet-soja",
    crop_key: "soja",
    name_fr: "Soja (Glycine max)",
    category: "Légumineuses & Oléagineux",
    cycle_days_min: 95,
    cycle_days_max: 125,
    climate_zones: ["Soudanien", "Guinéen"],
    seasons: ["Hivernage"],
    npk_needs: { N: 25, P: 60, K: 50 },
    water_needs_mm: 500,
    common_pests: ["Chenilles défoliatrices", "Punaises vertes phytophages", "Nématodes"],
    common_diseases: ["Rouille asiatique du soja", "Bactériose pustulaire", "Anthracnose"],
    recommended_varieties: ["TGX 1448-2E", "TGX 1904-6F", "Canarana"],
    yield_potential_t_ha: 2.8,
    notes: "Très prisé pour l'alimentation du bétail (tourteaux) et la nutrition humaine. Inoculation par Rhizobium recommandée sur terres vierges.",
    iconEmoji: "🌱",
  },
  {
    id: "sheet-coton",
    crop_key: "coton",
    name_fr: "Coton (Gossypium hirsutum)",
    category: "Cultures de rente",
    cycle_days_min: 130,
    cycle_days_max: 160,
    climate_zones: ["Soudanien", "Soudano-sahélien"],
    seasons: ["Hivernage"],
    npk_needs: { N: 80, P: 40, K: 60 },
    water_needs_mm: 650,
    common_pests: ["Chenille de la capsule (Helicoverpa armigera)", "Earias", "Mouche blanche (Bemisia tabaci)", "Jassides"],
    common_diseases: ["Bactériose du cotonnier (Xanthomonas)", "Flétrissement fusarien", "Virose bleue"],
    recommended_varieties: ["FK 37", "FK 64", "STAM 59 A"],
    yield_potential_t_ha: 2.8,
    notes: "Programme de protection phytosanitaire rigoureux par fenêtre de traitement (traitements raisonnés CAR). Première culture d'exportation.",
    iconEmoji: "☁️",
  },
  {
    id: "sheet-sesame",
    crop_key: "sesame",
    name_fr: "Sésame blanc / noir (Sesamum indicum)",
    category: "Cultures de rente & Oléagineux",
    cycle_days_min: 80,
    cycle_days_max: 105,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien"],
    seasons: ["Hivernage (semis mi-juillet)"],
    npk_needs: { N: 40, P: 30, K: 20 },
    water_needs_mm: 350,
    common_pests: ["Chenille tordeuse (Antigastra catalaunalis)", "Pucerons", "Criquets"],
    common_diseases: ["Phyllodie (phytoplasme)", "Bactériose", "Cercosporiose"],
    recommended_varieties: ["S-42", "Gimbi", "Humera", "Kola"],
    yield_potential_t_ha: 1.2,
    notes: "Semis superficiel à faible profondeur. Récolte délicate au moment du jaunissement des capsules inférieures pour éviter l'égrenage.",
    iconEmoji: "🌾",
  },
  {
    id: "sheet-tomate",
    crop_key: "tomate",
    name_fr: "Tomate maraîchère (Solanum lycopersicum)",
    category: "Maraîchage",
    cycle_days_min: 75,
    cycle_days_max: 110,
    climate_zones: ["Soudanien", "Soudano-sahélien", "Périmètres irrigués"],
    seasons: ["Contre-saison fraîche (Oct - Fév)", "Contre-saison chaude"],
    npk_needs: { N: 150, P: 80, K: 180 },
    water_needs_mm: 600,
    common_pests: ["Tuta absoluta (mineuse de la tomate)", "Mouche blanche (Bemisia)", "Nématodes gallicoles", "Noctuelles"],
    common_diseases: ["Mildiou (Phytophthora infestans)", "Flétrissement bactérien (Ralstonia)", "Virus TYLCV (feuilles jaunes en cuillère)"],
    recommended_varieties: ["Mongal F1", "Nirouz F1", "Cobra F1", "Tropimech", "Petomech"],
    yield_potential_t_ha: 45.0,
    notes: "Pépinière soignée sous voile anti-insectes indispensable. Tuteurage et paillage fortement recommandés pour préserver la qualité des fruits.",
    iconEmoji: "🍅",
  },
  {
    id: "sheet-oignon",
    crop_key: "oignon",
    name_fr: "Oignon violet / blanc (Allium cepa)",
    category: "Maraîchage",
    cycle_days_min: 90,
    cycle_days_max: 130,
    climate_zones: ["Soudano-sahélien", "Soudanien", "Vallées & barrages"],
    seasons: ["Contre-saison fraîche"],
    npk_needs: { N: 100, P: 60, K: 120 },
    water_needs_mm: 450,
    common_pests: ["Thrips du tabac et de l'oignon (Thrips tabaci)", "Mouche de l'oignon", "Nématodes"],
    common_diseases: ["Pourriture molle bactérienne", "Tache pourpre (Alternaria porri)", "Fonte des semis"],
    recommended_varieties: ["Violet de Galmi", "Goudami", "Prema F1", "Orient F1"],
    yield_potential_t_ha: 35.0,
    notes: "Arrêt strict de l'irrigation 10 à 15 jours avant la récolte pour assurer un ressuyage optimal et prolonger la conservation en magasin ventilé.",
    iconEmoji: "🧅",
  },
  {
    id: "sheet-gombo",
    crop_key: "gombo",
    name_fr: "Gombo (Abelmoschus esculentus)",
    category: "Maraîchage",
    cycle_days_min: 50,
    cycle_days_max: 90,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien", "Guinéen"],
    seasons: ["Hivernage", "Contre-saison irriguée"],
    npk_needs: { N: 60, P: 40, K: 50 },
    water_needs_mm: 400,
    common_pests: ["Altises des feuilles", "Vers de la capsule (Earias)", "Pucerons"],
    common_diseases: ["Oïdium des cucurbitacées et malvacées", "Enroulement des feuilles (Virose OELCV)"],
    recommended_varieties: ["Clemson Spineless", "Indiana", "Hire", "Sabourou"],
    yield_potential_t_ha: 15.0,
    notes: "Récolte continue tous les 2 à 3 jours pour stimuler la floraison et éviter la lignification des gousses. Haute valeur marchande locale.",
    iconEmoji: "🌱",
  },
];
