project_id = "dtfirensnobimhjqlngl"

[functions.calculate-crop-cycle]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
