import { MechanizationMachine, MechanizationService, MechanizationJob, FieldAgent } from "./types";

export const MECH_SERVICES: MechanizationService[] = [
  {
    id: "labour_lourd",
    name: "Labour lourd / Décompactage",
    category: "labour",
    baseRatePerHa: 35000,
    rateUnit: "par_ha",
    fuelPerHaLiters: 22,
    hoursPerHa: 2.5,
    description: "Charrue à disques 3 ou 4 corps pour enfouissement profond et bris de la semelle de labour.",
    iconName: "Tractor",
  },
  {
    id: "labour_standard",
    name: "Labour standard & Hersage",
    category: "labour",
    baseRatePerHa: 25000,
    rateUnit: "par_ha",
    fuelPerHaLiters: 15,
    hoursPerHa: 1.8,
    description: "Préparation complète du lit de semence, pulvérisation des mottes de terre et nivellement.",
    iconName: "Tractor",
  },
  {
    id: "semis_mecanise",
    name: "Semis motorisé de précision",
    category: "semis",
    baseRatePerHa: 18000,
    rateUnit: "par_ha",
    fuelPerHaLiters: 8,
    hoursPerHa: 1.2,
    description: "Semoir monograine pneumatique avec micro-fertilisation localisée (maïs, coton, soja, niébé).",
    iconName: "Wheat",
  },
  {
    id: "drone_pulverisation",
    name: "Traitement phytosanitaire par Drone",
    category: "pulverisation",
    baseRatePerHa: 10000,
    rateUnit: "par_ha",
    fuelPerHaLiters: 0,
    hoursPerHa: 0.3,
    description: "Pulvérisation ultra-bas volume par drone DJI Agras T40 sans tassement du sol, précision GPS RTK.",
    iconName: "Zap",
  },
  {
    id: "moisson_batteuse",
    name: "Moissonneuse-batteuse céréales",
    category: "recolte",
    baseRatePerHa: 45000,
    rateUnit: "par_ha",
    fuelPerHaLiters: 26,
    hoursPerHa: 1.5,
    description: "Moisson, battage et nettoyage simultanés pour riz, maïs et sorgho avec perte de grains < 2%.",
    iconName: "Wheat",
  },
  {
    id: "battage_champ",
    name: "Battage & Égrenage mobile",
    category: "battage",
    baseRatePerHa: 15000,
    rateUnit: "par_tonne",
    fuelPerHaLiters: 5,
    hoursPerHa: 0.8,
    description: "Batteuse-vanneuse mobile stationnaire animée par prise de force pour le riz paddy et le maïs.",
    iconName: "Layers",
  },
  {
    id: "transport_benne",
    name: "Transport & Logistique bord-champ",
    category: "transport",
    baseRatePerHa: 25000,
    rateUnit: "par_rotation",
    fuelPerHaLiters: 12,
    hoursPerHa: 2.0,
    description: "Évacuation des récoltes vers les hangars ou usines de transformation (remorque 8T ou camion benne).",
    iconName: "Truck",
  },
];

export const MECH_MACHINES: MechanizationMachine[] = [
  {
    id: "mach-1",
    title: "Massey Ferguson 375 4WD (75 CV)",
    category: "tracteur",
    powerHp: 75,
    brandModel: "Massey Ferguson 375",
    year: 2022,
    operatorIncluded: true,
    location: "Koupéla / Pouytenga",
    region: "Centre-Est",
    dailyCapacityHa: 5.5,
    pricePerHa: 25000,
    hourlyRate: 15000,
    status: "disponible",
    verifiedPartner: "Coopérative Méca-Sahel",
    rating: 4.9,
    completedJobs: 84,
    fuelType: "diesel",
    transmission: "Boîte mécanique 8x2 synchronisée",
    engineHours: 1240,
    imageUrl: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80",
    implementsIncluded: ["Charrue 3 disques", "Herse rotative 24 disques", "Semoir 4 rangs"],
  },
  {
    id: "mach-2",
    title: "John Deere 5075E Heavy Duty (75 CV)",
    category: "tracteur",
    powerHp: 75,
    brandModel: "John Deere 5075E",
    year: 2023,
    operatorIncluded: true,
    location: "Bobo-Dioulasso (Zone Cotonnière)",
    region: "Hauts-Bassins",
    dailyCapacityHa: 6.0,
    pricePerHa: 27000,
    hourlyRate: 16000,
    status: "disponible",
    verifiedPartner: "AgroMech Bobo Express",
    rating: 4.95,
    completedJobs: 112,
    fuelType: "diesel",
    transmission: "PowrReverser 12x12 hydraulique",
    engineHours: 850,
    imageUrl: "https://images.unsplash.com/photo-1594771804886-a933bb2d609b?auto=format&fit=crop&w=800&q=80",
    implementsIncluded: ["Charrue à disques renforcée", "Sous-soleuse 2 dents", "Remorque 6T"],
  },
  {
    id: "mach-3",
    title: "Drone Agricole DJI Agras T40 RTK (40L)",
    category: "drone",
    brandModel: "DJI Agras T40",
    year: 2024,
    operatorIncluded: true,
    location: "Bama / Vallée du Kou",
    region: "Hauts-Bassins",
    dailyCapacityHa: 18.0,
    pricePerHa: 10000,
    hourlyRate: 12000,
    status: "disponible",
    verifiedPartner: "MechDrone Burkina Tech",
    rating: 5.0,
    completedJobs: 67,
    fuelType: "electrique_batterie",
    transmission: "Propulsion coaxiale octocoptère",
    engineHours: 320,
    imageUrl: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80",
    implementsIncluded: ["Générateur rapide essence", "Batteries intelligentes x4", "Centrale RTK centimétrique"],
  },
  {
    id: "mach-4",
    title: "Moissonneuse-Batteuse Claas Dominator 130",
    category: "moissonneuse",
    powerHp: 130,
    brandModel: "Claas Dominator 130",
    year: 2021,
    operatorIncluded: true,
    location: "Pôle de Croissance de Bagré",
    region: "Centre-Est",
    dailyCapacityHa: 8.0,
    pricePerHa: 45000,
    status: "en_mission",
    verifiedPartner: "Bagré Agro Machinery Hub",
    rating: 4.85,
    completedJobs: 92,
    fuelType: "diesel",
    transmission: "Hydrostatique continue 3 gammes",
    engineHours: 1950,
    imageUrl: "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80",
    implementsIncluded: ["Table de coupe riz 3.6m", "Cueilleur maïs 4 rangs", "Broyeur de paille"],
  },
  {
    id: "mach-5",
    title: "Mahindra 6075 4WD (75 CV)",
    category: "tracteur",
    powerHp: 75,
    brandModel: "Mahindra 6075",
    year: 2023,
    operatorIncluded: true,
    location: "Dédougou / Grenier du Mouhoun",
    region: "Boucle du Mouhoun",
    dailyCapacityHa: 5.8,
    pricePerHa: 26000,
    hourlyRate: 15500,
    status: "disponible",
    verifiedPartner: "Mouhoun Agri-Services",
    rating: 4.9,
    completedJobs: 73,
    fuelType: "diesel",
    transmission: "Synchro Shuttle 15x15",
    engineHours: 640,
    imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80",
    implementsIncluded: ["Charrue 4 disques", "Semoir pneumatique", "Gyrobroyeur"],
  },
  {
    id: "mach-6",
    title: "Motoculteur Multifonction Yanmar YM14 (14 CV)",
    category: "motoculteur",
    powerHp: 14,
    brandModel: "Yanmar YM14 Diesel",
    year: 2022,
    operatorIncluded: true,
    location: "Ouagadougou / Loumbila (Maraîchage)",
    region: "Plateau-Central",
    dailyCapacityHa: 1.5,
    pricePerHa: 20000,
    hourlyRate: 8000,
    status: "disponible",
    verifiedPartner: "Maraîchers Unis du Faso",
    rating: 4.75,
    completedJobs: 45,
    fuelType: "diesel",
    transmission: "Mécanique 6 avant / 2 arrière",
    engineHours: 410,
    imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80",
    implementsIncluded: ["Fraise rotative arrière", "Charrue brabant", "Petite remorque 1T"],
  },
];

export const INITIAL_JOBS: MechanizationJob[] = [
  {
    id: "JOB-2026-081",
    serviceType: "Labour standard & Hersage",
    parcelName: "Parcelle Nord - Bas-fond (5.0 ha)",
    areaHa: 5.0,
    totalCost: 125000,
    depositAmount: 37500,
    paymentMethod: "orange_money",
    escrowStatus: "acompte_bloque",
    jobStatus: "operateur_en_route",
    operatorName: "Salif Ouédraogo (Conducteur certifié)",
    operatorPhone: "+226 70 12 34 56",
    fieldAgentName: "Moussa Sawadogo (Agent Terrain KoobNaaba)",
    fieldAgentPhone: "+226 76 99 88 11",
    scheduledDate: "Aujourd'hui à 08h30",
    machineName: "Massey Ferguson 375 (75 CV)",
    engineHoursStart: 1420.5,
    notes: "Sol meuble après premières pluies. Priorité aux bordures est pour éviter l'érosion.",
  },
  {
    id: "JOB-2026-074",
    serviceType: "Traitement phytosanitaire Drone DJI",
    parcelName: "Parcelle Cotonnière Plateau (4.2 ha)",
    areaHa: 4.2,
    totalCost: 42000,
    depositAmount: 42000,
    paymentMethod: "moov_money",
    escrowStatus: "solde_debloque",
    jobStatus: "termine",
    operatorName: "Inoussa Kaboré (Télé-pilote certifié)",
    operatorPhone: "+226 65 44 33 22",
    fieldAgentName: "Fatimata Traoré (Agente Terrain KoobNaaba)",
    fieldAgentPhone: "+226 78 11 22 33",
    scheduledDate: "16 Septembre 2026",
    machineName: "DJI Agras T40 RTK",
    engineHoursStart: 42.0,
    engineHoursEnd: 43.2,
    notes: "Traitement biologique bio-pesticide pulvérisé avec succès en 1h15.",
  },
];

export const FIELD_AGENTS: FieldAgent[] = [
  {
    id: "FA-01",
    name: "Moussa Sawadogo",
    zone: "Koupéla, Pouytenga & Zorgho",
    phone: "+226 76 99 88 11",
    whatsapp: "+226 76 99 88 11",
    languages: ["Mooré", "Français"],
    activeVillages: 14,
    assignedOperators: 8,
  },
  {
    id: "FA-02",
    name: "Fatimata Traoré",
    zone: "Bobo-Dioulasso, Bama & Toussiana",
    phone: "+226 78 11 22 33",
    whatsapp: "+226 78 11 22 33",
    languages: ["Dioula", "Français"],
    activeVillages: 19,
    assignedOperators: 12,
  },
  {
    id: "FA-03",
    name: "Boukary Diallo",
    zone: "Dédougou, Nouna & Boromo",
    phone: "+226 70 55 44 22",
    whatsapp: "+226 70 55 44 22",
    languages: ["Dioula", "Fulfuldé", "Français"],
    activeVillages: 16,
    assignedOperators: 9,
  },
  {
    id: "FA-04",
    name: "Alassane Zongo",
    zone: "Bagré Pôle & Tenkodogo",
    phone: "+226 64 33 22 11",
    whatsapp: "+226 64 33 22 11",
    languages: ["Mooré", "Bissa", "Français"],
    activeVillages: 12,
    assignedOperators: 7,
  },
];
